// <auto-generated />
using BooksApp_Spring2024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksAppSpring2024.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20240116142924_creatingCategoriesTableAndSeedingWithData")]
    partial class creatingCategoriesTableAndSeedingWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksApp_Spring2024.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "This is the description for the Science Fiction Category",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "This is the description for the Technology Category",
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "This is the description for the History Category",
                            Name = "History"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
